kind: pipeline
type: docker
name: Publish

platform:
  os: linux
  arch: arm64

steps:
  - name: Build
    image: node:alpine
    environment:
      NPM_REGISTRY:
        from_secret: npm_registry_cache
    commands:
      - npm install
      - npm run compile
  - name: Publish
    image: plugins/npm
    settings:
      username: markrawls
      password:
        from_secret: npm_password
      email:
        from_secret: npm_email
