kind: pipeline
type: docker
name: Publish

platform:
  os: linux
  arch: arm64

steps:
  - name: Build
    image: node:16-alpine
    environment:
      NPM_REGISTRY:
        from_secret: npm_registry_cache
    commands:
      - npm install
      - npm run compile
  - name: Publish
    image: plugins/npm
    settings:
      username:
        from_secret: NPM_USERNAME
      password:
        from_secret: NPM_PASSWORD
      email: ari@aricodes.net
